todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    # path('edit/<int:pk>/', views.edit, name='edit'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

wunderlist/urls.py
from django.contrib import admin
from django.urls import path, include
from decouple import config
from todos import views

token = config("angi_bot")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('token/', views.telegram),
]

todos/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
    """Model definition for Todo."""

    title = models.CharField(max_length=150)
    due_date = models.DateField()

    def __str__(self):
        """Unicode representation of Todo."""
        return self.title

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Todo
from decouple import config
import telegram
import requests
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

synastry = config("synastrybot")
angi = config("angi_bot")
park = config("park")
jimmy = config("jimmy")

def index(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos,
    }
    return render(request, 'todos/index.html', context)

# def new(request):
#     return render(request, 'todos/new.html')

def create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')

        Todo.objects.create(
            title=title, 
            due_date=due_date
        )
        synastry_bot = telegram.Bot(token = synastry)
        angi_bot = telegram.Bot(token = angi)
        synastry_bot.sendMessage(chat_id = park, text=f"todo: {title} due_date: {due_date}")
        angi_bot.sendMessage(chat_id = park, text=f"todo: {title} due_date: {due_date}")
        synastry_bot.sendMessage(chat_id = jimmy, text=f"todo: {title} due_date: {due_date}")
        angi_bot.sendMessage(chat_id = jimmy, text=f"todo: {title} due_date: {due_date}")
        return redirect('todos:index')
        
    else:
        return render(request, 'todos/create.html')

def update(request, pk):
    # todo = Todo.objects.get(id=pk)
    todo = get_object_or_404(Todo, id=pk)
    context = {
        'todo': todo
    }
    if request.method == "POST":
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')

        todo.title = title
        todo.due_date = due_date
        todo.save()
        base_url = "https://api.telegram.org/bot"
        for bot in [synastry, angi]:
            for user in [park, jimmy]:
                url = base_url + f'{bot}/sendMessage?text=title: {title} due date: {due_date}&chat_id={user}'
                requests.post(url)
        return redirect('todos:index')
        

    else:
        return render(request, 'todos/update.html', context)

def delete(request, pk):
    todo = get_object_or_404(Todo, id=pk)
    todo.delete()

    return redirect('todos:index')

csrf_exempt
def telegram(request):
    print(request.method)
    print(request)
    return HttpResponse("Goooood!")

todos/templates/todos/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Wunderlist</title>
</head>

<body>
    <div class="container my-3">
        <a href="{% url 'todos:create' %}" class="btn btn-info">글 작성</a>
        <a href="{% url 'todos:index' %}" class="btn btn-primary">홈</a>
        {% block body %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    </div>
</body>

</html>

todos/templates/todos/create.html
{% extends 'todos/base.html' %}


{% block body %}
<h1 class="mt-5 mb-3">New</h1>
<form action="{% url 'todos:create' %}" method="post">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="date" name="due-date">
    <input type="submit">
</form>
{% endblock body %}

todos/templates/todos/index.html
{% extends 'todos/base.html' %}


{% block body %}
<h1 class="mt-5">Task</h1>
<div class="container my-3">
    {% for todo in todos  %}
    <div class="card">
        <div class="card-body d-flex justify-content-between">
            <h5 class="card-title">{{ todo.title }}</h5>
            <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
            <div>
                Due to <small class="mr-3"><b> {{ todo.due_date }}</b></small>
                <a href="{% url 'todos:update' todo.id %}" class="btn btn-success">수정</a>
                <a href="{% url 'todos:delete' todo.id %}" class="btn btn-warning">삭제</a>
            </div>

        </div>
    </div>
    {% endfor %}
</div>



{% endblock body %}

todos/templates/todos/update.html
{% extends 'todos/base.html' %}


{% block body %}
<h1 class="mt-5 mb-3">Edit</h1>
<form action="{% url 'todos:update' todo.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="title" value="{{ todo.title }}">
    <input type="date" name="due-date" value="{{ todo.due_date | date:'Y-m-d'}}">
    <input type="submit">
</form>
{% endblock body %}